name: "React 101 Sonarqube"
on:
  # workflow_dispatch:

  push:
    branches:
      - main

jobs:
  SonarCloudScan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Version
        uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_KEY }}
            -Dsonar.projectKey=${{ secrets.SONAR_KEY }}